project_id = "nwmpstvoutkjshhhtmrk"

[functions.generate-qa]
verify_jwt = true

[functions.validate-answers]
verify_jwt = true

[functions.fetch-article-preview]
verify_jwt = true

[functions.evaluate-trust-score]
verify_jwt = true

[functions.transcribe-youtube]
verify_jwt = false

[functions.test-supadata]
verify_jwt = false

[functions.classify-content]
verify_jwt = true
